### PR TITLE
feat: inlcude request in onPost function

### PR DESCRIPTION
**Pull request by BryanGK**
## Proposed Changes

- include the request object in the onPost function

### CODE REVIEW

**Comment by kriscooke** [comment]
@BryanGK Is there a corresponding test improvement we could include to validate the fix?

**Comment by BryanGK** [comment]
@kriscooke Yes, likely. What would I test for? That the request is in the onPost function?

**Review by wenzowski — APPROVED** [review]
Given there's not currently any test coverage for `onPost` let's not make adding tests in scope for this PR but let's definitely get a tech debt card going and follow up with net new test coverage.

**Comment by BryanGK** [comment]
@wenzowski issue #377 has been created for increasing unit test coverage

**Pull request merged**
